runtime: python

env: flex
entrypoint: gunicorn --worker-class eventlet -w 1 main:app

beta_settings:
  cloud_sql_instances: "wits-wagers:us-central1:dpetek-witts"

runtime_config:
  python_version: 3
